# Generated by Django 4.2.24 on 2025-09-07 07:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="check_in",
            new_name="check_in_date",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="check_out",
            new_name="check_out_date",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="guests",
            new_name="number_of_guests",
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="amenities",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="listing",
            name="bathrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="listing",
            name="bedrooms",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="listing",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="house_rules",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="max_guests",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="listing",
            name="photos",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField()),
                ("photos", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("listing", "user")},
            },
        ),
    ]
